<a href="https://colab.research.google.com/github/zeynepyilmazz/DataScienceBootcamp/blob/main/03.PythonDataScienceLibraries/01.BasicsOfNumPyArray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**(1)** Create 3 lists representing house features, each list containing 10 values. First one for squaremeter of house, second one for rooms and last one for price. Then, create an array combining these lists.

In [ ]:
import numpy as np

In [ ]:

squaremeter = np.array([120,100,80,65,110,90,100,135,75,100])
rooms = np.array([3,2,2,1,3,2,2,3,1,2])
price = np.array([500,400,450,300,300,400,500,600,250,400])
all = np.array([squaremeter,rooms,price])
print(all)

[[120 100  80  65 110  90 100 135  75 100]
 [  3   2   2   1   3   2   2   3   1   2]
 [500 400 450 300 300 400 500 600 250 400]]


**(2)** Transpose the array you have created, so that every line can represent features of one house.

In [ ]:
all_new = all.transpose()
print(all_new)

[[120   3 500]
 [100   2 400]
 [ 80   2 450]
 [ 65   1 300]
 [110   3 300]
 [ 90   2 400]
 [100   2 500]
 [135   3 600]
 [ 75   1 250]
 [100   2 400]]


**(3)** Display the shape of the array and explain what it means.

In [ ]:
print(squaremeter.shape) #(10,) tek boyutlu 10 elemanlı bir dizi
print(rooms.shape)       #(10,) tek boyutlu 10 elemanlı bir dizi
print(price.shape)       #(10,) tek boyutlu 10 elemanlı bir dizi
print(all.shape)         #(3, 10) iki boyutlu 3 satır 10 sütundan oluşan 3 x 10 = 30 elemanlı bir dizi
print(all_new.shape)     #(10, 3) iki boyutlu 10 satır 3 sütundan oluşan 10 x 3 = 30 elemanlı bir dizi

(10,)
(10,)
(10,)
(3, 10)
(10, 3)


**(4)** Write a function that returns an array of ones with zeros where both row and column numbers are even. Sample array is below. Number of rows and columns will be entered as parameters.

```python
    shape(6 x 5) --> [[1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]]
```

In [ ]:
def shape(x,y):
  liste = np.zeros((x,y))
  for i in range(0,x):
    for j in range(0,y):
      if (i % 2 == 0 or j % 2 == 0):
        liste[i][j] = 1
      else:
        liste[i][j] = 0
  return liste

print(shape(6,5))

[[1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1.]]
