<a href="https://colab.research.google.com/github/zeynepyilmazz/DataScienceBootcamp/blob/main/03.PythonDataScienceLibraries/03.MathematicalOperationsONumPyArrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**(1)** Load the array you saved in the previous lesson from the disk.

In [1]:
import numpy as np

In [2]:
array = np.load("array.npy")
print(array)


[[0.000e+00 0.000e+00 0.000e+00 ... 4.000e+00 7.000e+00 0.000e+00]
 [1.000e+00 0.000e+00 0.000e+00 ... 4.100e+00 7.000e+00 0.000e+00]
 [2.000e+00 0.000e+00 0.000e+00 ... 4.400e+00 7.000e+00 0.000e+00]
 ...
 [6.571e+03 4.000e+00 0.000e+00 ... 4.800e+00 2.000e+00 0.000e+00]
 [6.572e+03 3.000e+00 0.000e+00 ... 5.200e+00 2.000e+00 0.000e+00]
 [6.573e+03 2.000e+00 0.000e+00 ... 4.400e+00 2.000e+00 0.000e+00]]


**(2)** Display the mean and the standard deviation for each column.

In [3]:
print(array.mean(axis = 0))
print(array.std(axis = 0))

[3.28650000e+03 5.49950198e+03 0.00000000e+00 8.86826894e-02
 0.00000000e+00 3.84616969e+01 3.30841796e+01 2.49830271e+01
 0.00000000e+00 1.01451171e+01 0.00000000e+00 0.00000000e+00
 4.46759963e+00 6.77654396e+00 0.00000000e+00]
[1.89775031e+03 3.97651842e+03 0.00000000e+00 4.06686207e-01
 0.00000000e+00 1.63396498e+00 6.28004726e+00 2.77566002e+01
 0.00000000e+00 1.27978334e+01 0.00000000e+00 0.00000000e+00
 4.85681616e-01 5.41160601e+00 0.00000000e+00]


**(3)** Subtract 1, 25, 25, 10, 4 from columns in order. (Remember it can be subtracted in one line of code.)

In [5]:
del_array = np.delete(array,[1,25,25,10,4],axis = 0)
print(del_array[0:25,])


[[ 0.      0.      0.      0.      0.     36.8578 44.4161 16.97    0.
   7.      0.      0.      4.      7.      0.    ]
 [ 2.      0.      0.      0.      0.     37.6878 37.4016 10.27    0.
   7.      0.      0.      4.4     7.      0.    ]
 [ 3.      0.      0.      0.      0.     37.2003 30.4376 78.07    0.
   7.      0.      0.      4.      7.      0.    ]
 [ 5.      0.      0.      0.      0.     36.4171 28.6991 14.86    0.
   7.      0.      0.      4.1     7.      0.    ]
 [ 6.      0.      0.      0.      0.     36.0535 31.2135 36.68    0.
   7.      0.      0.      5.2     7.      0.    ]
 [ 7.      0.      0.      0.      0.     37.1958 30.6241 50.33    0.
   7.      0.      0.      4.8     7.      0.    ]
 [ 8.      0.      0.      0.      0.     36.9653 27.7633  6.93    0.
   7.      0.      0.      4.3     7.      0.    ]
 [ 9.      0.      0.      0.      0.     38.893  26.4483 11.62    0.
   7.      0.      0.      4.2     7.      0.    ]
 [11.      0.      0.      0.   

**(4)** Multiply each element by 2. (Remember it can be multiplied in one line of code.)

In [6]:
multiply_array = array * 2
print(multiply_array)

[[0.0000e+00 0.0000e+00 0.0000e+00 ... 8.0000e+00 1.4000e+01 0.0000e+00]
 [2.0000e+00 0.0000e+00 0.0000e+00 ... 8.2000e+00 1.4000e+01 0.0000e+00]
 [4.0000e+00 0.0000e+00 0.0000e+00 ... 8.8000e+00 1.4000e+01 0.0000e+00]
 ...
 [1.3142e+04 8.0000e+00 0.0000e+00 ... 9.6000e+00 4.0000e+00 0.0000e+00]
 [1.3144e+04 6.0000e+00 0.0000e+00 ... 1.0400e+01 4.0000e+00 0.0000e+00]
 [1.3146e+04 4.0000e+00 0.0000e+00 ... 8.8000e+00 4.0000e+00 0.0000e+00]]
